# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReDebug.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(518, 503)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit_info = QtWidgets.QTextEdit(Form)
        self.textEdit_info.setObjectName("textEdit_info")
        self.verticalLayout.addWidget(self.textEdit_info)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit_re = QtWidgets.QTextEdit(Form)
        self.textEdit_re.setObjectName("textEdit_re")
        self.verticalLayout.addWidget(self.textEdit_re)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_findall = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_findall.setObjectName("pushButton_findall")
        self.horizontalLayout.addWidget(self.pushButton_findall)
        self.pushButton_search = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.pushButton_match = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_match.setObjectName("pushButton_match")
        self.horizontalLayout.addWidget(self.pushButton_match)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_newtext = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_newtext.setFont(font)
        self.label_newtext.setObjectName("label_newtext")
        self.verticalLayout_4.addWidget(self.label_newtext)
        self.textEdit_newText = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_newText.setObjectName("textEdit_newText")
        self.verticalLayout_4.addWidget(self.textEdit_newText)
        self.pushButton_sub = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.verticalLayout_4.addWidget(self.pushButton_sub)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_split = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_split.setObjectName("pushButton_split")
        self.verticalLayout_3.addWidget(self.pushButton_split)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textEdit_result = QtWidgets.QTextEdit(Form)
        self.textEdit_result.setObjectName("textEdit_result")
        self.verticalLayout.addWidget(self.textEdit_result)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "欲匹配文本"))
        self.textEdit_info.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">你好 hello word 123456789 ./*-</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">~拜拜</p></body></html>"))
        self.label_2.setText(_translate("Form", "正则表达式"))
        self.pushButton_findall.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">匹配全部 返回匹配到的数量和值</span></p></body></html>"))
        self.pushButton_findall.setText(_translate("Form", "寻找全部 - findall"))
        self.pushButton_search.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">匹配一次，返回匹配到的值与位置</span></p></body></html>"))
        self.pushButton_search.setText(_translate("Form", "寻找一次 - search"))
        self.pushButton_match.setToolTip(_translate("Form", "<html><head/><body><p>只匹配<span style=\" color:#ff007f;\">开头</span> 返回值和位置</p></body></html>"))
        self.pushButton_match.setText(_translate("Form", "匹配开头 - match"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "匹配"))
        self.label_newtext.setText(_translate("Form", "新文本"))
        self.pushButton_sub.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">匹配成功后以</span><span style=\" font-size:11pt; color:#ff007f;\">新文本</span><span style=\" font-size:11pt;\">替换</span></p></body></html>"))
        self.pushButton_sub.setText(_translate("Form", "替换 - sub"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "替换"))
        self.pushButton_split.setToolTip(_translate("Form", "<html><head/><body><p>根据正则表达式<span style=\" color:#ff007f;\">打断</span></p></body></html>"))
        self.pushButton_split.setText(_translate("Form", "打断 - split"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "打断"))
        self.label_3.setText(_translate("Form", "结果"))

